# Generated by Django 4.2.7 on 2025-09-24 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_projectactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('link_type', models.CharField(choices=[('github', 'GitHub Repository'), ('gitlab', 'GitLab Repository'), ('bitbucket', 'Bitbucket Repository'), ('documentation', 'Documentation'), ('deployment', 'Live Deployment'), ('staging', 'Staging Environment'), ('design', 'Design Files'), ('figma', 'Figma Design'), ('trello', 'Trello Board'), ('slack', 'Slack Channel'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='projects.project')),
            ],
            options={
                'ordering': ['link_type', 'title'],
            },
        ),
    ]
