# Generated by Django 4.2.7 on 2025-09-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the file is active and visible'),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the file is active and visible'),
        ),
    ]
