# Generated by Django 4.2.7 on 2025-09-26 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_projecttopic_topicnote_topicmedia_topiclink_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('problem_statement', models.TextField(blank=True, help_text='What problem does this idea solve?')),
                ('solution_overview', models.TextField(blank=True, help_text='High-level overview of the solution')),
                ('target_audience', models.TextField(blank=True, help_text='Who would benefit from this idea?')),
                ('market_potential', models.TextField(blank=True, help_text='Market size, opportunity, etc.')),
                ('revenue_model', models.TextField(blank=True, help_text='How would this generate revenue?')),
                ('competition_analysis', models.TextField(blank=True, help_text='Existing competitors and differentiation')),
                ('technical_requirements', models.TextField(blank=True, help_text='Key technical requirements and constraints')),
                ('estimated_effort', models.CharField(blank=True, help_text='Time/effort estimate', max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('concept', 'Concept'), ('in_development', 'In Development'), ('implemented', 'Implemented'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_ideas', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(blank=True, related_name='ideas', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('research', 'Research'), ('reference', 'Reference'), ('inspiration', 'Inspiration'), ('competitor', 'Competitor'), ('tool', 'Tool'), ('other', 'Other')], default='reference', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ideas.idea')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ideas.idea')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
